config/routes.rb
Rails.application.routes.draw do

  get 'users/index'

  get 'users/show'

  get 'pages/contact'

  get 'pages/about'

  get 'pages/faq'

  get 'homepage/index'

  devise_for :users

  root 'welcome#index'

  resources :champions do
    resources :guides
  end

  resources :topics

  %w(contact about faq).each do |page|
    get page => "pages##{page}"
  end

end

app/models/champion.rb
class Champion < ActiveRecord::Base
  has_many :guides
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/guide.rb
class Guide < ActiveRecord::Base
  belongs_to :champion
  belongs_to :user
  has_many :comments, as: :commentable

  # acts_as_votable

  # def score
  #   self.get_upvotes.count - self.get_downvotes.count
  # end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable

  # acts_as_votable

  # def score
  #   self.get_upvotes.count - self.get_downvotes.count
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :guides
  #user is not invovled in polymorphic association
  has_many :comments
  has_many :topics

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  def index
    @champions = Champion.all
    # we wont need this tho
  end

  def show
    @champion = Champion.find(params[:id])
    @guides = @champion.guides
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  def index
    #wont really need any info bc it would be weird to see all guides for all champions in a single page, too much
  end

  def show #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.find(params[:id])
  end

  def new #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.new
  end

  def edit #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.find(params[:id])
  end

  def create #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.new(guide_params)
    @guide.user_id = current_user[:id]
    if @guide.save
      redirect_to champion_guide_path(@champion,@guide)
    else
      render "new"
    end
  end


  def update #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.find(params[:id])
      if @guide.update(guide_params)
        redirect_to champion_guide_path(@champion,@guide)
      else
        render 'edit'
      end
  end

  def destroy #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.find(params[:id])
    @guide.destroy
    redirect_to champion_path(@champion)
  end

  private
  def guide_params
    params.require(:guide).permit(:title, :champion_advice, :item_build)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
  end

  def faq
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user[:id]
      if @topic.save
        redirect_to @topic
      else
        render "new"
      end
  end

  def update
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(current_user.id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @disable_nav = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoL Guide</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'lol.jpeg' %>
</head>
<%= render 'partials/header' unless @disable_nav %>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
a little bio about myself and maybe a pciture (cause im so good looking :D ) <br>
<div>
the real cross fit
<div id="cross">
  <img src="/images/jesuscrossfit.jpg" alt="image with rounded corners">
</div>

</div>

app/views/pages/contact.html.erb
<div class="container">
have a form for emailing me
</div>

app/views/pages/faq.html.erb
<div class="container">
Not sure but we can put random questions about page and maybe about myself
</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/homepage/index">LoLGuide</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Summoner Name...">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= topics_path %>">Topics</a></li>
        <li><a href="<%= champions_path %>">Champion Guides</a></li>
        <li><a href="<%= about_path %>">About Me</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if user_signed_in? %>
              <li><a href="<%=users_show_path(@user)%>">My Profile</a></li>
              <li><a href="<%=destroy_user_session_path %>">Sign Out</a></li>
            <% else %>
              <li><a href="<%= new_user_session_path %>">Login</a></li>
              <li><a href="<%= new_user_registration_path %>">Sign Up</a></li>
            <% end %>
            <li><a href="<%= faq_path %>">FAQ's</a></li>
            <li class="divider"></li>
            <li><a href="<%= contact_path %>">Contact Us</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>