config/routes.rb
Rails.application.routes.draw do

  get 'users/index'

  get 'users/show'

  get 'pages/contact'

  get 'pages/about'

  get 'pages/faq'

  get 'homepage/index'

  devise_for :users

  root 'welcome#index'

  resources :champions do
    resources :guides
  end

  resources :topics

  %w(contact about faq).each do |page|
    get page => "pages##{page}"
  end

end

app/models/champion.rb
class Champion < ActiveRecord::Base
  has_many :guides
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/guide.rb
class Guide < ActiveRecord::Base
  belongs_to :champion
  belongs_to :user
  has_many :comments, as: :commentable

  # acts_as_votable

  # def score
  #   self.get_upvotes.count - self.get_downvotes.count
  # end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable

  # acts_as_votable

  # def score
  #   self.get_upvotes.count - self.get_downvotes.count
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :guides
  #user is not invovled in polymorphic association
  has_many :comments
  has_many :topics

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  def index
    @champions = Champion.all
    # we wont need this tho
  end

  def show
    @champion = Champion.find(params[:id])
    @guides = @champion.guides
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  def index
    #wont really need any info bc it would be weird to see all guides for all champions in a single page, too much
  end

  def show #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.find(params[:id])
  end

  def new #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.new
  end

  def edit #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.find(params[:id])
  end

  def create #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.new(guide_params)
    @guide.user_id = current_user[:id]
    if @guide.save
      redirect_to champion_guide_path(@champion,@guide)
    else
      render "new"
    end
  end


  def update #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.find(params[:id])
      if @guide.update(guide_params)
        redirect_to champion_guide_path(@champion,@guide)
      else
        render 'edit'
      end
  end

  def destroy #works
    @champion = Champion.find(params[:champion_id])
    @guide = @champion.guides.find(params[:id])
    @guide.destroy
    redirect_to champion_path(@champion)
  end

  private
  def guide_params
    params.require(:guide).permit(:title, :champion_advice, :item_build)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
  end

  def faq
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user[:id]
      if @topic.save
        redirect_to @topic
      else
        render "new"
      end
  end

  def update
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(current_user.id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @disable_nav = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/champions/index.html.erb
<div class="container">
  <h2><b>Champions</b></h2><br>

  <div class="row">
    <div class="col-xs-2">
      <a href="/champions/1" class="thumbnail">
        <img src="/images/championicons/Aatrox.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/2" class="thumbnail">
        <img src="/images/championicons/Ahri.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/3" class="thumbnail">
        <img src="/images/championicons/Akali.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/4" class="thumbnail">
        <img src="/images/championicons/Alistar.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/5" class="thumbnail">
        <img src="/images/championicons/Amumu.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/6" class="thumbnail">
        <img src="/images/championicons/Anivia.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/7" class="thumbnail">
        <img src="/images/championicons/Annie.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/8" class="thumbnail">
        <img src="/images/championicons/Ashe.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/9" class="thumbnail">
        <img src="/images/championicons/Azir.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/10" class="thumbnail">
        <img src="/images/championicons/Blitzcrank.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/11" class="thumbnail">
        <img src="/images/championicons/Brand.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/12" class="thumbnail">
        <img src="/images/championicons/Braum.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/13" class="thumbnail">
        <img src="/images/championicons/Caitlyn.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/14" class="thumbnail">
        <img src="/images/championicons/Cassiopeia.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/15" class="thumbnail">
        <img src="/images/championicons/Chogath.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/16" class="thumbnail">
        <img src="/images/championicons/Corki.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/17" class="thumbnail">
        <img src="/images/championicons/Darius.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/18" class="thumbnail">
        <img src="/images/championicons/Diana.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/19" class="thumbnail">
        <img src="/images/championicons/DrMundo.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/20" class="thumbnail">
        <img src="/images/championicons/Draven.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/21" class="thumbnail">
        <img src="/images/championicons/Elise.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/22" class="thumbnail">
        <img src="/images/championicons/Evelynn.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/23" class="thumbnail">
        <img src="/images/championicons/Ezreal.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/24" class="thumbnail">
        <img src="/images/championicons/FiddleSticks.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/25" class="thumbnail">
        <img src="/images/championicons/Fiora.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/26" class="thumbnail">
        <img src="/images/championicons/Fizz.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/27" class="thumbnail">
        <img src="/images/championicons/Galio.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/28" class="thumbnail">
        <img src="/images/championicons/Gangplank.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/29" class="thumbnail">
        <img src="/images/championicons/Garen.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/30" class="thumbnail">
        <img src="/images/championicons/Gnar.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/31" class="thumbnail">
        <img src="/images/championicons/Gragas.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/32" class="thumbnail">
        <img src="/images/championicons/Graves.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/33" class="thumbnail">
        <img src="/images/championicons/Hecarim.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/34" class="thumbnail">
        <img src="/images/championicons/Heimerdinger.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/35" class="thumbnail">
        <img src="/images/championicons/Irelia.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/36" class="thumbnail">
        <img src="/images/championicons/Janna.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/37" class="thumbnail">
        <img src="/images/championicons/JarvanIV.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/38" class="thumbnail">
        <img src="/images/championicons/Jax.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/39" class="thumbnail">
        <img src="/images/championicons/Jayce.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/40" class="thumbnail">
        <img src="/images/championicons/Jinx.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/41" class="thumbnail">
        <img src="/images/championicons/Kalista.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/42" class="thumbnail">
        <img src="/images/championicons/Karma.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/43" class="thumbnail">
        <img src="/images/championicons/Karthus.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/44" class="thumbnail">
        <img src="/images/championicons/Kassadin.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/45" class="thumbnail">
        <img src="/images/championicons/Katarina.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/46" class="thumbnail">
        <img src="/images/championicons/Kayle.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/47" class="thumbnail">
        <img src="/images/championicons/Kennen.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/48" class="thumbnail">
        <img src="/images/championicons/Khazix.png" alt="125x125">
      </a>
    </div>
     <div class="col-xs-2">
      <a href="/champions/49" class="thumbnail">
        <img src="/images/championicons/KogMaw.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/50" class="thumbnail">
        <img src="/images/championicons/Leblanc.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/51" class="thumbnail">
        <img src="/images/championicons/LeeSin.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/52" class="thumbnail">
        <img src="/images/championicons/Leona.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/53" class="thumbnail">
        <img src="/images/championicons/Lissandra.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/54" class="thumbnail">
        <img src="/images/championicons/Lucian.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/55" class="thumbnail">
        <img src="/images/championicons/Lulu.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/56" class="thumbnail">
        <img src="/images/championicons/Lux.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/57" class="thumbnail">
        <img src="/images/championicons/Malphite.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/58" class="thumbnail">
        <img src="/images/championicons/Malzahar.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/59" class="thumbnail">
        <img src="/images/championicons/Maokai.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/60" class="thumbnail">
        <img src="/images/championicons/MasterYi.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/61" class="thumbnail">
        <img src="/images/championicons/MissFortune.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/62" class="thumbnail">
        <img src="/images/championicons/Mordekaiser.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/63" class="thumbnail">
        <img src="/images/championicons/Morgana.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/64" class="thumbnail">
        <img src="/images/championicons/Nami.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/65" class="thumbnail">
        <img src="/images/championicons/Nasus.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/66" class="thumbnail">
        <img src="/images/championicons/Nautilus.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/67" class="thumbnail">
        <img src="/images/championicons/Nidalee.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/68" class="thumbnail">
        <img src="/images/championicons/Nocturne.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/69" class="thumbnail">
        <img src="/images/championicons/Nunu.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/70" class="thumbnail">
        <img src="/images/championicons/Olaf.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/71" class="thumbnail">
        <img src="/images/championicons/Orianna.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/72" class="thumbnail">
        <img src="/images/championicons/Pantheon.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/73" class="thumbnail">
        <img src="/images/championicons/Poppy.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/74" class="thumbnail">
        <img src="/images/championicons/Quinn.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/75" class="thumbnail">
        <img src="/images/championicons/Rammus.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/76" class="thumbnail">
        <img src="/images/championicons/RekSai.png" alt="125x125">
      </a>
    </div>
    <div class="col-xs-2">
      <a href="/champions/77" class="thumbnail">
        <img src="/images/championicons/Renekton.png" alt="125x125">
      </a>
    </div>


</div>

app/views/champions/show.html.erb
<div class="container">
  <% @guides.each do |guide| %>
    <%= @champion.id %>
    <%= @champion.name %>
    <%= guide.id %>
    <%= link_to guide.title, champion_guide_path(@champion,guide.id) %><br>
  <% end %>

  <%= link_to "Create New Guide", new_champion_guide_path(@champion), class: 'btn btn-primary btn-xs' %>
</div>

app/views/guides/edit.html.erb
<div class="container">
  <%= form_for :guide, url: champion_guide_path(@champion, @guide), method: :patch do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :champion_advice %><br>
      <%= f.text_area :champion_advice %>
    </p>

    <p>
      <%= f.label :item_build %><br>
      <%= f.text_area :item_build %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>

  <%= link_to 'Back', champion_guide_path(@champion,@guide) %>
</div>

app/views/guides/index.html.erb
guide index we will not use, delete later3

app/views/guides/new.html.erb
<div class="container">
  <%= form_for([@champion,@guide]) do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :champion_advice %><br>
      <%= f.text_field :champion_advice %>
    </p>
    <p>
      <%= f.label :item_build %><br>
      <%= f.text_field :item_build %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/guides/show.html.erb
<div class="container">
  <h3>Title: </h3><%= @guide.title %>
  <h3>Champion Advice: </h3><%= @guide.champion_advice %>
  <h3>Item Build: </h3><%= @guide.item_build %>
  <h4>CHAMP ID <%= @guide.champion_id %>
  <h4>GUIDE ID <%= @guide.id %> </h4>
  <h4>user ID <%= @guide.user_id %> </h4>

  <%= link_to "View All Guides",champion_path(@champion), class: 'btn btn-primary btn-xs' %>

  <% if current_user.id == @guide.user_id %>
    <%= link_to "Delete", champion_guide_path(@champion, @guide), :confirm => "Are you sure?", :method => :delete, class: 'btn btn-primary btn-xs' %>
    <%= link_to "Edit", edit_champion_guide_path(@champion, @guide), class: 'btn btn-primary btn-xs' %>
  <% else %>
    <%= "you cant edit or delete, not the owwner" %>
  <% end %>

</div>

app/views/homepage/index.html.erb
<div class="row">
  <div class="col-md-1">1 column</div>
  <div class="col-md-1">1 column</div>
  <div class="col-md-1">1 column</div>
  <div class="col-md-1">1 column</div>
  <div class="col-md-1">1 column</div>
  <div class="col-md-1">1 column</div>
  <div class="col-md-1">1 column</div>
  <div class="col-md-1">1 column</div>
  <div class="col-md-1">1 column</div>
  <div class="col-md-1">1 column</div>
  <div class="col-md-1">1 column</div>
  <div class="col-md-1">1 column</div>
</div>

<div id="main-container" class="container-fluid">
  <div class="row">
    <div id="main-content" class="col-md-9">
      CURRENTLY IN PROCESS <br>
      Homepage will include: miscallenous stuff (like youtube videos and such)<br>
      header with champion guides for champselect, search for a specific player and topic/discussion threads<br>
      find cool background and icon and pictures<br>
      maybe use bootstrap (SASS)?<br>
      Although this site is primarily being made for LoL, hopefully after completetion I will have time to add more games<br>
      *** NOTE!! This is made just for fun, and to practice RoR. please dont sue me for any images or copyright infringement. <3 <br>
      asdasdjasldjalsdkjaskldjaskldjaslkdjlaksdjlkasjdlkasjdlaskdljalksjdalksdjalksdjlkasdjlaksd
      <br><%= link_to 'Champs', champions_path, class: 'btn btn-primary btn-xs' %>
    </div>
    <div id="sidebar" class="col-md-3">
      <h3> THIS WILL BE A SIDE BAR </h3>
      <p> not sure what will be here yet </p>
      <p> maybe links or stuff </p>
      ASLKDJAKSJDKLAJSDLKAJSDKLAJSDLKAJSDKLJASDLKJASDLKJASDLKJASDLKJASDKLJALSKDJLKASJDLKASJDLKASJDKLj
    </div>

  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <h2> Recent Discussions </h2><br>
  <% @topics.each do |x| %>
    <%= link_to x.title, topic_path(x.id) %><br>
  <% end %>
</div>

<%= link_to "create new", new_topic_path, class: 'btn btn-primary btn-xs' %><br>

SHOW ALL THE TOPICS

app/views/topics/new.html.erb
<div class="container">
  <%= form_for @topic do |f| %>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %>
      <%= f.text_field :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/topics/show.html.erb
<div class="container">
  Title: <%= @topic.title %><br>
  <%= @topic.body %>

  <% if current_user.id == @topic.user_id %>
    <%= link_to "delete", topic_path(@topic), :confirm => "Are you sure?", :method => :delete, class: 'btn btn-primary btn-xs' %>
  <% else %>
    <%= "you cant do anything" %>
  <% end %>

</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <h1> User Profile Page </h2>

  Welcome <%= @user.first_name %>
  <%= @user.last_name %><br>

  email: <%= @user.email %><br>

  <%= link_to "edit profile", edit_user_registration_path(@user), class: 'btn btn-primary btn-xs' %>
</div>

user/show

app/views/welcome/index.html.erb
<div class="picture">
  <%= link_to "Enter Here", homepage_index_path, class: 'btn btn-primary btn-xs' %>
</div>